application: gumroad
version: 1
runtime: python
api_version: 1

handlers:
    
- url: .+/ 
  script: slashmurderer.py
    
- url: /static
  static_dir: static
   
- url: /downloads
  static_dir: downloads
 
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: .*
  script: main.py
  secure: optional